models:
  - name: ranker
    source: hf
    hf_repo: Careem/xfy-quik-ranker-v1
    params_path: inference_params
    params_format: orbax_standard
    artifact_name: ranker
    artifact_dir: compiled
    default_platform: gpu
    max_batch_size: 32
